name = "StructLH"
uuid = "10801879-faf9-5fee-b4da-d4f48ef6194b"
authors = ["hendri54 <hendricksl@protonmail.com>"]
version = "1.1"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.8, 0.9"
Documenter = "0.27"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
